package org.inframesh.phost.model.entry;

import org.inframesh.phost.model.AbstractDTO;
import org.inframesh.phost.util.annotation.Column;
import org.inframesh.phost.util.annotation.JdbcType;
import org.inframesh.phost.util.annotation.Table;

/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: DATA_DICT
 *
 * Generated by ormapper plug-in
 */

@Table(name="DATA_DICT")
public class DataDict extends AbstractDTO
{
    private static final Long serialVersionUID = -1536511063186330764L;

	@Column(pk=true, name="DICT_ID", type=JdbcType.BIGINT, nullable=false)
    private Long dictId;

    @Column(name="DICT_TYPE", type=JdbcType.VARCHAR)
    private String dictType;

    @Column(name="DICT_CODE", type=JdbcType.CHARACTER)
    private String dictCode;

    @Column(name="DICT_HINT", type=JdbcType.VARCHAR)
    private String dictHint;

    @Column(name="DICT_HINT_CHS", type=JdbcType.VARCHAR)
    private String dictHintChs;
    
    @Column(name="NOTE1", type=JdbcType.VARCHAR)
    private String note1;
    
    @Column(name="NOTE2", type=JdbcType.VARCHAR)
    private String note2;


    public void setDictId(Long dictId) {
        this.dictId = dictId;
    }

    public Long getDictId() {
        return this.dictId;
    }

    public void setDictType(String dictType) {
        this.dictType = dictType;
    }

    public String getDictType() {
        return this.dictType;
    }

    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    public String getDictCode() {
        return this.dictCode;
    }

    public void setDictHint(String dictHint) {
        this.dictHint = dictHint;
    }

    public String getDictHint() {
        return this.dictHint;
    }

    public void setDictHintChs(String dictHintChs) {
        this.dictHintChs = dictHintChs;
    }

    public String getDictHintChs() {
        return this.dictHintChs;
    }
    
    public void setNote1(String note1) {
        this.note1 = note1;
    }

    public String getNote1() {
        return this.note1;
    }
    
    public void setNote2(String note2) {
        this.note2 = note2;
    }

    public String getNote2() {
        return this.note2;
    }

}
