package org.inframesh.phost.model.entry;

import org.inframesh.phost.model.AbstractDTO;
import org.inframesh.phost.util.annotation.Column;
import org.inframesh.phost.util.annotation.JdbcType;
import org.inframesh.phost.util.annotation.Table;

/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: DOWNLOAD
 *
 * Generated by ormapper plug-in
 */

@Table(name="DOWNLOAD")
public class Download extends AbstractDTO
{
    private static final Long serialVersionUID = 3977037105580769859L;

    @Column(pk=true, name="DOWNLOAD_ID", type=JdbcType.BIGINT, nullable=false)
    private Long downloadId;

    @Column(name="PROJECT_ID", type=JdbcType.BIGINT)
    private Long projectId;

    @Column(name="SUMMARY", type=JdbcType.VARCHAR)
    private String summary;

    @Column(name="FILE_NAME", type=JdbcType.VARCHAR)
    private String fileName;

    @Column(name="FILE_SIZE", type=JdbcType.VARCHAR)
    private String fileSize;

    @Column(name="UPLOADED", type=JdbcType.VARCHAR)
    private String uploaded;

    @Column(name="DOWNLOAD_COUNT", type=JdbcType.BIGINT)
    private Long downloadCount;
    
    private String[] labels;


    public void setDownloadId(Long downloadId) {
        this.downloadId = downloadId;
    }

    public Long getDownloadId() {
        return this.downloadId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectId() {
        return this.projectId;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getFileSize() {
        return this.fileSize;
    }

    public void setUploaded(String uploaded) {
        this.uploaded = uploaded;
    }

    public String getUploaded() {
        return this.uploaded;
    }

    public void setDownloadCount(Long downloadCount) {
        this.downloadCount = downloadCount;
    }

    public Long getDownloadCount() {
        return this.downloadCount;
    }

	/**
	 * @param labels the labels to set
	 */
	public void setLabels(String[] labels) {
		this.labels = labels;
	}

	/**
	 * @return the labels
	 */
	public String[] getLabels() {
		return labels;
	}

}
