package org.inframesh.phost.model.entry;

import org.inframesh.phost.model.AbstractDTO;
import org.inframesh.phost.util.annotation.Column;
import org.inframesh.phost.util.annotation.JdbcType;
import org.inframesh.phost.util.annotation.Table;

/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: PROJECT_MEMBER
 *
 * Generated by ormapper plug-in
 */

@Table(name="PROJECT_MEMBER")
public class ProjectMember extends AbstractDTO
{
    private static final Long serialVersionUID = 4339697949667831318L;
    
    public static final String OWNER = "1";
    public static final String COMMITTER = "2";
    public static final String CONTRIBUTOR = "3";

	@Column(pk=true, name="PROJECT_MEMBER_ID", type=JdbcType.BIGINT, nullable=false)
    private Long projectMemberId;

    @Column(name="PROJECT_ID", type=JdbcType.BIGINT, nullable=false)
    private Long projectId;

    @Column(name="USER_ID", type=JdbcType.BIGINT, nullable=false)
    private Long userId;

    @Column(name="ROLE", type=JdbcType.CHARACTER, nullable=false)
    private String role;


    public void setProjectMemberId(Long projectMemberId) {
        this.projectMemberId = projectMemberId;
    }

    public Long getProjectMemberId() {
        return this.projectMemberId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    public Long getProjectId() {
        return this.projectId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getRole() {
        return this.role;
    }

}
