package org.inframesh.phost.model.entry;

import org.inframesh.phost.model.AbstractDTO;
import org.inframesh.phost.util.annotation.Column;
import org.inframesh.phost.util.annotation.JdbcType;
import org.inframesh.phost.util.annotation.Table;

/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: USER
 *
 * Generated by ormapper plug-in
 */

@Table(name="USER")
public class User extends AbstractDTO
{
    private static final Long serialVersionUID = 1589770408869150862L;

	@Column(pk=true, name="USER_ID", type=JdbcType.BIGINT, nullable=false)
    private Long userId;

    @Column(name="EMAIL", type=JdbcType.VARCHAR, nullable=false)
    private String email;

    @Column(name="PASSWORD", type=JdbcType.VARCHAR)
    private String password;


    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return this.email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPassword() {
        return this.password;
    }

}
