package org.inframesh.phost.model.entry;

import org.inframesh.phost.model.AbstractDTO;
import org.inframesh.phost.util.annotation.Column;
import org.inframesh.phost.util.annotation.JdbcType;
import org.inframesh.phost.util.annotation.Table;

/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: WIKI
 *
 * Generated by ormapper plug-in
 */

@Table(name="WIKI")
public class Wiki extends AbstractDTO
{
    private static final Long serialVersionUID = -6552791374954022298L;

	@Column(pk=true, name="WIKI_ID", type=JdbcType.BIGINT, nullable=false)
    private Long wikiId;

    @Column(name="PAGE_NAME", type=JdbcType.VARCHAR)
    private String pageName;

    @Column(name="CONTENT", type=JdbcType.LONG_VARCHAR)
    private String content;

    @Column(name="COMMIT_LOG", type=JdbcType.LONG_VARCHAR)
    private String commitLog;


    public void setWikiId(Long wikiId) {
        this.wikiId = wikiId;
    }

    public Long getWikiId() {
        return this.wikiId;
    }

    public void setPageName(String pageName) {
        this.pageName = pageName;
    }

    public String getPageName() {
        return this.pageName;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return this.content;
    }

    public void setCommitLog(String commitLog) {
        this.commitLog = commitLog;
    }

    public String getCommitLog() {
        return this.commitLog;
    }

}
