/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: EXTRAS
 *
 * Generated by ormapper plug-in
 */

@Table(name="EXTRAS")
public class Extras
{
    @Column(pk=true, name="EXTRAS_ID", type=JdbcType.BIGINT, nullable=false)
    private long extrasId;

    @Column(name="MODULE_ID", type=JdbcType.BIGINT)
    private long moduleId;

    @Column(name="MODULE_TYPE", type=JdbcType.VARCHAR)
    private String moduleType;

    @Column(name="CATEGORY", type=JdbcType.VARCHAR)
    private String category;

    @Column(name="TEXT", type=JdbcType.VARCHAR)
    private String text;

    @Column(name="CONTENT", type=JdbcType.VARCHAR)
    private String content;


    public void setExtrasId(long extrasId) {
        this.extrasId = extrasId;
    }

    public long getExtrasId() {
        return this.extrasId;
    }

    public void setModuleId(long moduleId) {
        this.moduleId = moduleId;
    }

    public long getModuleId() {
        return this.moduleId;
    }

    public void setModuleType(String moduleType) {
        this.moduleType = moduleType;
    }

    public String getModuleType() {
        return this.moduleType;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getCategory() {
        return this.category;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getText() {
        return this.text;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return this.content;
    }

}
