/**
 * @author ${user}
 *
 * ${tags}
 */

/**
 * Table Name: DOWNLOAD
 *
 * Generated by ormapper plug-in
 */

@Table(name="DOWNLOAD")
public class Download
{
    @Column(pk=true, name="DOWNLOAD_ID", type=JdbcType.BIGINT, nullable=false)
    private long downloadId;

    @Column(name="PROJECT_ID", type=JdbcType.BIGINT)
    private long projectId;

    @Column(name="SUMMARY", type=JdbcType.VARCHAR)
    private String summary;

    @Column(name="FILE_NAME", type=JdbcType.VARCHAR)
    private String fileName;

    @Column(name="FILE_SIZE", type=JdbcType.VARCHAR)
    private String fileSize;

    @Column(name="UPLOADED", type=JdbcType.VARCHAR)
    private String uploaded;

    @Column(name="DOWNLOAD_COUNT", type=JdbcType.BIGINT)
    private long downloadCount;


    public void setDownloadId(long downloadId) {
        this.downloadId = downloadId;
    }

    public long getDownloadId() {
        return this.downloadId;
    }

    public void setProjectId(long projectId) {
        this.projectId = projectId;
    }

    public long getProjectId() {
        return this.projectId;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    public String getSummary() {
        return this.summary;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getFileSize() {
        return this.fileSize;
    }

    public void setUploaded(String uploaded) {
        this.uploaded = uploaded;
    }

    public String getUploaded() {
        return this.uploaded;
    }

    public void setDownloadCount(long downloadCount) {
        this.downloadCount = downloadCount;
    }

    public long getDownloadCount() {
        return this.downloadCount;
    }

}
